services:
  panel-next:
    build: .
    container_name: panel-next
    network_mode: host
    volumes:
    - ./docker-conf:/app/conf
    - ./service/uploads:/app/uploads
    - ./service/database:/app/database
    restart: always
